service: sls-22-feb
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  delfrinando:
    handler: index.delfrinando
    events:
      - httpApi:
          path: /delfrinando
          method: get

  pranata:
    handler: index.pranata
    events:
      - httpApi:
          path: /pranata
          method: get

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline

