service: sls-22-feb
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /delfrinando
          method: post

  pranata:
    handler: index.handler
    events:
      - httpApi:
          path: /pranata
          method: post

plugins:
  - serverless-offline

